# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae60fd22403167c242817b3e99714ce931928bdef6c84cd5eaf0228e11a488ef4ccb891b23b89ed1b734aeb6137388963137c3e6bc7184ad8e565cc09573cc6
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: 1b0bd72b3fabb84802535bd3b70d19981974743f916b16c60d1beec73f7c81508ee2e43d017f3277050be317c119e88595da726781d0b98ba16845bf94e7ac70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
